clc;
A = randi([10,99],5,6);
fprintf("The base matrix is: \n");
disp(A);
b = A(end,:);
fprintf("The last row of the matrix is: \n");
disp(b);
c = A(end,(end:-1:1));
fprintf("The last row of the matrix, in reverse, is: \n");
disp(c);
d = A(end:-1:1, [1 2]);
fprintf("The first two columns of the matrix, in reverse row order, are: \n");
disp(d);
E = A((end:-1:1),:);
fprintf("The matrix, in reverse row order, is: \n");
disp(E);
F = A(:,(end:-1:1));
fprintf("The matrix, in reverse column order, is: \n");
disp(F);
%%A(3,4) = [];