function figHandles = plotWindowedMoments(results, signalName, outputFolder)
% PLOTWINDOWEDMOMENTS
% Plot and save windowed-moment results.
%
% INPUTS:
%   results      - output from calculateWindowedMoments
%   signalName   - name used in plot titles and filenames
%   outputFolder - folder in which .fig and .png files are saved
%
% OUTPUT:
%   figHandles   - handles of the four created figures


%% Validate inputs

if nargin < 2 || isempty(signalName)
    signalName = 'signal';
end

if nargin < 3 || isempty(outputFolder)
    outputFolder = pwd;
end

if ~isfolder(outputFolder)
    mkdir(outputFolder);
end


%% Safe filename

safeSignalName = char(string(signalName));

safeSignalName = regexprep( ...
    safeSignalName, ...
    '[^\w-]', ...
    '_');

if isempty(safeSignalName)
    safeSignalName = 'signal';
end


%% Plot definitions

momentFields = { ...
    'mean', ...
    'rms', ...
    'skewness', ...
    'kurtosis'};

plotTitles = { ...
    'Windowed Mean', ...
    'Windowed RMS', ...
    'Windowed Skewness', ...
    'Windowed Excess Kurtosis'};

yLabels = { ...
    'Mean', ...
    'RMS', ...
    'Skewness', ...
    'Excess Kurtosis'};

fileTags = { ...
    'mean', ...
    'rms', ...
    'skewness', ...
    'excess_kurtosis'};

nMoments = numel(momentFields);

figHandles = gobjects(nMoments, 1);


%% Create each moment figure separately

for m = 1:nMoments

    fieldName = momentFields{m};

    values = results.(fieldName).values;
    globalValue = results.(fieldName).global;
    radValues = results.(fieldName).rad;

    nWindows = size(values, 2);


    %% Create figure

    figHandles(m) = figure( ...
        'Name', ...
        sprintf('%s - %s', ...
        char(string(signalName)), ...
        plotTitles{m}), ...
        'Color', ...
        'w');

    hold on;


    %% Plot each window size

    legendEntries = cell(1, nWindows + 1);

    for w = 1:nWindows

        plot( ...
            results.time, ...
            values(:, w), ...
            'LineWidth', ...
            1.1);

        legendEntries{w} = sprintf( ...
            '%.4g s window | RAD = %.4g', ...
            results.windowSizesSec(w), ...
            radValues(w));

    end


    %% Global reference line

    yline( ...
        globalValue, ...
        '--', ...
        'LineWidth', ...
        1.5);

    legendEntries{end} = sprintf( ...
        'Global = %.4g', ...
        globalValue);


    %% Format graph

    grid on;

    xlabel('Time (s)');
    ylabel(yLabels{m});

    title( ...
        sprintf('%s - %s', ...
        char(string(signalName)), ...
        plotTitles{m}), ...
        'Interpreter', ...
        'none');

    legend( ...
        legendEntries, ...
        'Location', ...
        'best');

    hold off;


    %% Save FIG

    baseFilename = sprintf( ...
        '%s_windowed_%s', ...
        safeSignalName, ...
        fileTags{m});

    figPath = fullfile( ...
        outputFolder, ...
        [baseFilename '.fig']);

    savefig( ...
        figHandles(m), ...
        figPath);


    %% Save PNG

    pngPath = fullfile( ...
        outputFolder, ...
        [baseFilename '.png']);

    exportgraphics( ...
        figHandles(m), ...
        pngPath, ...
        'Resolution', ...
        300);

end

end